const { createClient } = supabase;
const sb = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });

const state = { lang: localStorage.getItem('portal_lang') || 'ar', profile:null, wallet:null, tx:[], inv:[], fr:[], wr:[] };
const T = {
  ar:{brand:'Investment Portal',brandSub:'منطقة الأعضاء',memberArea:'منطقة الأعضاء',signIn:'تسجيل الدخول',signUp:'إنشاء حساب',welcomeBack:'مرحباً بعودتك',loginSub:'سجّل الدخول إلى حسابك بأمان.',username:'اسم المستخدم',password:'كلمة المرور',forgot:'نسيت كلمة المرور؟',reset:'إعادة التعيين',createAccount:'أنشئ حسابك',signupSub:'أنشئ حساباً جديداً للوصول إلى بوابتك.',fullName:'الاسم الكامل',email:'البريد الإلكتروني',confirmPassword:'تأكيد كلمة المرور',agree:'أوافق على الشروط وسياسة الاستخدام.',dashboard:'لوحة التحكم',investments:'استثماراتي',fundAccount:'تمويل الحساب',withdraw:'السحب',transactions:'المعاملات',profile:'الملف الشخصي',settings:'الإعدادات',logout:'تسجيل الخروج',securePortal:'بوابة آمنة',hello:'مرحباً',dashboardIntro:'تابع رصيدك واستثماراتك وطلباتك من مكان واحد.',availableBalance:'الرصيد المتاح',totalInvested:'إجمالي الاستثمار',earnings:'الأرباح المسجلة',recentTransactions:'آخر المعاملات',myInvestments:'استثماراتي',investmentSub:'الاستثمارات المسجلة في حسابك.',fundSub:'أرسل طلب تمويل ليتم مراجعته من الإدارة.',amount:'المبلغ (KWD)',method:'طريقة الدفع',reference:'المرجع',notes:'ملاحظات',submitRequest:'إرسال الطلب',myFundingRequests:'طلبات التمويل',withdrawSub:'أرسل طلب سحب من رصيدك المتاح.',destination:'بيانات الاستلام',myWithdrawalRequests:'طلبات السحب',transactionsSub:'سجل العمليات المسجلة على حسابك.',profileSub:'حدّث معلومات ملفك الشخصي.',phone:'رقم الهاتف',saveChanges:'حفظ التغييرات',settingsSub:'تفضيلات حسابك.',language:'اللغة',languageSub:'اختر لغة واجهة الحساب.',avatar:'الصورة الشخصية',chooseImage:'اختيار صورة',saveImage:'حفظ الصورة',noData:'لا توجد بيانات بعد.',loading:'جارٍ التحميل...',requestSent:'تم إرسال الطلب بنجاح.',saved:'تم حفظ التغييرات.',loginFailed:'تعذر تسجيل الدخول.',signupDone:'تم إنشاء الحساب. تحقق من بريدك الإلكتروني قبل تسجيل الدخول.',passwordMismatch:'كلمتا المرور غير متطابقتين.',invalidAmount:'أدخل مبلغاً صحيحاً.',logoutDone:'تم تسجيل الخروج.',resetSent:'إذا كان البريد مسجلاً، ستصلك تعليمات إعادة التعيين.',resetPassword:'تعيين كلمة مرور جديدة',newPassword:'كلمة المرور الجديدة',confirmNewPassword:'تأكيد كلمة المرور الجديدة',updatePassword:'تحديث كلمة المرور',passwordUpdated:'تم تحديث كلمة المرور.',error:'حدث خطأ. حاول مرة أخرى.',pending:'قيد المراجعة',approved:'مقبول',rejected:'مرفوض',active:'نشط',completed:'مكتمل',cancelled:'ملغى',credit:'إضافة',debit:'خصم',funding:'تمويل',withdrawal:'سحب',investment:'استثمار',earning:'أرباح',selectMethod:'اختر الطريقة',bankTransfer:'تحويل بنكي',crypto:'أصول رقمية',other:'أخرى',enterDestination:'أدخل بيانات الاستلام',fileTooLarge:'حجم الصورة كبير جداً.',imageSaved:'تم حفظ الصورة.'},
  en:{brand:'Investment Portal',brandSub:'Member Area',memberArea:'Member Area',signIn:'Sign in',signUp:'Create account',welcomeBack:'Welcome back',loginSub:'Sign in securely to your account.',username:'Username',password:'Password',forgot:'Forgot your password?',reset:'Reset it',createAccount:'Create your account',signupSub:'Create a new account to access your portal.',fullName:'Full name',email:'Email address',confirmPassword:'Confirm password',agree:'I agree to the terms and usage policy.',dashboard:'Dashboard',investments:'My investments',fundAccount:'Fund account',withdraw:'Withdraw',transactions:'Transactions',profile:'Profile',settings:'Settings',logout:'Log out',securePortal:'Secure portal',hello:'Hello',dashboardIntro:'Track your balance, investments and requests in one place.',availableBalance:'Available balance',totalInvested:'Total invested',earnings:'Recorded earnings',recentTransactions:'Recent transactions',myInvestments:'My investments',investmentSub:'Investments recorded on your account.',fundSub:'Submit a funding request for administrative review.',amount:'Amount (KWD)',method:'Payment method',reference:'Reference',notes:'Notes',submitRequest:'Submit request',myFundingRequests:'Funding requests',withdrawSub:'Submit a withdrawal request from your available balance.',destination:'Receiving details',myWithdrawalRequests:'Withdrawal requests',transactionsSub:'A record of transactions posted to your account.',profileSub:'Update your profile information.',phone:'Phone number',saveChanges:'Save changes',settingsSub:'Your account preferences.',language:'Language',languageSub:'Choose your account interface language.',avatar:'Profile picture',chooseImage:'Choose image',saveImage:'Save picture',noData:'No data yet.',loading:'Loading...',requestSent:'Request submitted successfully.',saved:'Changes saved.',loginFailed:'Unable to sign in.',signupDone:'Account created. Check your email before signing in.',passwordMismatch:'Passwords do not match.',invalidAmount:'Enter a valid amount.',logoutDone:'Signed out.',resetSent:'If that email is registered, reset instructions have been sent.',resetPassword:'Set a new password',newPassword:'New password',confirmNewPassword:'Confirm new password',updatePassword:'Update password',passwordUpdated:'Password updated.',error:'Something went wrong. Please try again.',pending:'Pending',approved:'Approved',rejected:'Rejected',active:'Active',completed:'Completed',cancelled:'Cancelled',credit:'Credit',debit:'Debit',funding:'Funding',withdrawal:'Withdrawal',investment:'Investment',earning:'Earnings',selectMethod:'Choose a method',bankTransfer:'Bank transfer',crypto:'Digital assets',other:'Other',enterDestination:'Enter receiving details',fileTooLarge:'Image is too large.',imageSaved:'Picture saved.'}
};
const tr=k=>T[state.lang][k]||k;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function applyLang(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=tr(e.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>e.placeholder=tr(e.dataset.i18nPlaceholder));document.getElementById('langAr')?.classList.toggle('active',state.lang==='ar');document.getElementById('langEn')?.classList.toggle('active',state.lang==='en');if(document.getElementById('topLang'))document.getElementById('topLang').textContent=state.lang==='ar'?'English':'العربية';document.title=tr('brand');}
function setLang(l){state.lang=l;localStorage.setItem('portal_lang',l);applyLang();if(state.profile)showPage(document.querySelector('#nav button.active')?.dataset.page||'dashboard');}
function toast(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3200)}
function fmt(n){return `KWD ${Number(n||0).toLocaleString(state.lang==='ar'?'ar-KW':'en-KW',{minimumFractionDigits:3,maximumFractionDigits:3})}`}
function initials(n){return (n||'U').trim().split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function statusBadge(s){return `<span class="badge">${esc(tr(s))}</span>`}
async function currentUser(){const {data:{user}}=await sb.auth.getUser();return user}
async function loadData(){const user=await currentUser();if(!user)return;const [p,w,tx,inv,fr,wr]=await Promise.all([sb.from('profiles').select('*').eq('id',user.id).single(),sb.from('wallets').select('*').eq('user_id',user.id).single(),sb.from('transactions').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50),sb.from('investments').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),sb.from('funding_requests').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),sb.from('withdrawal_requests').select('*').eq('user_id',user.id).order('created_at',{ascending:false})]);state.profile=p.data;state.wallet=w.data;state.tx=tx.data||[];state.inv=inv.data||[];state.fr=fr.data||[];state.wr=wr.data||[];if(p.error)console.error(p.error);render()}
function render(){const p=state.profile||{};document.getElementById('userNameTop').textContent=p.full_name||p.username||'—';document.getElementById('userEmailTop').textContent=p.email||'—';document.getElementById('heroName').textContent=p.full_name||p.username||'—';setAvatar('avatarSmall',p);setAvatar('profileAvatar',p);const w=state.wallet||{};document.getElementById('balance').textContent=fmt(w.balance);document.getElementById('invested').textContent=fmt(w.total_invested);document.getElementById('earnings').textContent=fmt(w.recorded_earnings);renderRows('recentTx',state.tx.slice(0,5),x=>`<div class="row"><div><strong>${esc(tr(x.type))}</strong><small>${esc(x.description||x.reference||'')}</small></div><div class="amount ${['credit','funding','earning'].includes(x.type)?'positive':'negative'}">${['credit','funding','earning'].includes(x.type)?'+':'-'} ${fmt(x.amount)}</div></div>`);renderRows('transactionList',state.tx,x=>`<div class="row"><div><strong>${esc(tr(x.type))}</strong><small>${new Date(x.created_at).toLocaleString(state.lang==='ar'?'ar-KW':'en-KW')} · ${esc(x.description||'')}</small></div><div>${statusBadge(x.status)} <span class="amount">${fmt(x.amount)}</span></div></div>`);renderRows('recentInv',state.inv.slice(0,5),x=>`<div class="row"><div><strong>${esc(x.plan_name)}</strong><small>${esc(tr(x.status))}</small></div><div class="amount">${fmt(x.amount)}</div></div>`);renderRows('investmentList',state.inv,x=>`<div class="row"><div><strong>${esc(x.plan_name)}</strong><small>${esc(tr(x.status))} · ${new Date(x.created_at).toLocaleDateString(state.lang==='ar'?'ar-KW':'en-KW')}</small></div><div class="amount">${fmt(x.amount)}</div></div>`);renderRows('fundingList',state.fr,x=>`<div class="row"><div><strong>${esc(tr('funding'))} · ${fmt(x.amount)}</strong><small>${esc(x.payment_method)} ${x.reference?'· '+esc(x.reference):''}</small></div>${statusBadge(x.status)}</div>`);renderRows('withdrawalList',state.wr,x=>`<div class="row"><div><strong>${esc(tr('withdrawal'))} · ${fmt(x.amount)}</strong><small>${esc(x.method)}</small></div>${statusBadge(x.status)}</div>`);document.getElementById('profileName').value=p.full_name||'';document.getElementById('profilePhone').value=p.phone||'';document.getElementById('profileEmail').value=p.email||'';document.getElementById('profileUsername').value=p.username||'';}
function setAvatar(id,p){const e=document.getElementById(id);if(!e)return;if(p.avatar_url){e.innerHTML=`<img src="${esc(p.avatar_url)}" alt="">`;e.classList.add('has-image')}else{e.textContent=initials(p.full_name||p.username);e.classList.remove('has-image')}}
function renderRows(id,arr,fn){const e=document.getElementById(id);if(e)e.innerHTML=arr.length?arr.map(fn).join(''):`<div class="empty">${tr('noData')}</div>`}
async function emailForUsername(username){const {data,error}=await sb.rpc('get_email_for_username',{p_username:username});if(error)throw error;return data}
async function loginWithUsername(username,password){const email=await emailForUsername(username);if(!email)throw new Error(tr('loginFailed'));const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error}
async function signup(){const name=document.getElementById('signupName').value.trim(),username=document.getElementById('signupUsername').value.trim(),email=document.getElementById('signupEmail').value.trim().toLowerCase(),password=document.getElementById('signupPassword').value,confirm=document.getElementById('signupConfirm').value;if(password!==confirm){toast(tr('passwordMismatch'));return}if(!/^[A-Za-z0-9_.-]{3,30}$/.test(username)){toast(tr('error'));return}const existing=await emailForUsername(username);if(existing)throw new Error(state.lang==='ar'?'اسم المستخدم مستخدم بالفعل.':'Username is already in use.');const r=await sb.auth.signUp({email,password,options:{data:{username,full_name:name}}});if(r.error)throw r.error;toast(tr('signupDone'));document.getElementById('showLogin').click()}
function showAuth(tab){document.getElementById('loginForm').classList.toggle('hidden',tab!=='login');document.getElementById('signupForm').classList.toggle('hidden',tab!=='signup');document.getElementById('showLogin').classList.toggle('active',tab==='login');document.getElementById('showSignup').classList.toggle('active',tab==='signup')}
async function showApp(){document.getElementById('authView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');await loadData()}
function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));document.getElementById(`page-${page}`).classList.remove('hidden');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.getElementById('pageTitle').textContent=tr(document.querySelector(`#nav button[data-page="${page}"]`)?.dataset.i18n||page)}
async function requestFund(e){e.preventDefault();const amount=Number(document.getElementById('fundAmount').value);if(!(amount>0)){toast(tr('invalidAmount'));return}const user=await currentUser();const {error}=await sb.from('funding_requests').insert({user_id:user.id,amount,payment_method:document.getElementById('fundMethod').value,reference:document.getElementById('fundRef').value.trim(),notes:document.getElementById('fundNotes').value.trim()});if(error)throw error;toast(tr('requestSent'));e.target.reset();await loadData()}
async function requestWithdraw(e){e.preventDefault();const amount=Number(document.getElementById('withdrawAmount').value),w=Number(state.wallet?.balance||0);if(!(amount>0)||amount>w){toast(tr('invalidAmount'));return}const user=await currentUser();const {error}=await sb.from('withdrawal_requests').insert({user_id:user.id,amount,method:document.getElementById('withdrawMethod').value,destination:document.getElementById('withdrawDestination').value.trim(),notes:document.getElementById('withdrawNotes').value.trim()});if(error)throw error;toast(tr('requestSent'));e.target.reset();await loadData()}
async function saveProfile(e){e.preventDefault();const user=await currentUser();const {error}=await sb.from('profiles').update({full_name:document.getElementById('profileName').value.trim(),phone:document.getElementById('profilePhone').value.trim()}).eq('id',user.id);if(error)throw error;toast(tr('saved'));await loadData()}
async function uploadAvatar(){const input=document.getElementById('avatarFile'),file=input.files[0];if(!file)return;if(file.size>2*1024*1024){toast(tr('fileTooLarge'));return}if(!file.type.startsWith('image/'))return;const user=await currentUser();const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${user.id}/avatar.${ext}`;const {error:up}=await sb.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(up)throw up;const {data}=sb.storage.from('avatars').getPublicUrl(path);const {error}=await sb.from('profiles').update({avatar_url:data.publicUrl}).eq('id',user.id);if(error)throw error;toast(tr('imageSaved'));await loadData()}
async function updatePassword(e){e.preventDefault();const a=document.getElementById('newPassword').value,b=document.getElementById('confirmNewPassword').value;if(a.length<8||a!==b){toast(tr('passwordMismatch'));return}const {error}=await sb.auth.updateUser({password:a});if(error)throw error;toast(tr('passwordUpdated'));location.hash='';document.getElementById('resetView').classList.add('hidden');}
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('showLogin').onclick=()=>showAuth('login');document.getElementById('showSignup').onclick=()=>showAuth('signup');document.getElementById('langAr').onclick=()=>setLang('ar');document.getElementById('resetLangAr').onclick=()=>setLang('ar');document.getElementById('resetLangEn').onclick=()=>setLang('en');document.getElementById('langEn').onclick=()=>setLang('en');document.getElementById('topLang').onclick=()=>setLang(state.lang==='ar'?'en':'ar');document.getElementById('settingsAr').onclick=()=>setLang('ar');document.getElementById('settingsEn').onclick=()=>setLang('en');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('[data-page-jump]').forEach(b=>b.onclick=()=>showPage(b.dataset.pageJump));document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();try{await loginWithUsername(document.getElementById('loginUsername').value.trim(),document.getElementById('loginPassword').value);await showApp()}catch(err){console.error(err);toast(err.message||tr('loginFailed'))}};document.getElementById('signupForm').onsubmit=async e=>{e.preventDefault();try{await signup()}catch(err){console.error(err);toast(err.message||tr('error'))}};document.getElementById('fundForm').onsubmit=async e=>{try{await requestFund(e)}catch(err){toast(err.message||tr('error'))}};document.getElementById('withdrawForm').onsubmit=async e=>{try{await requestWithdraw(e)}catch(err){toast(err.message||tr('error'))}};document.getElementById('profileForm').onsubmit=async e=>{try{await saveProfile(e)}catch(err){toast(err.message||tr('error'))}};document.getElementById('avatarFile').onchange=async()=>{try{await uploadAvatar()}catch(err){toast(err.message||tr('error'))}};document.getElementById('resetForm').onsubmit=async e=>{try{await updatePassword(e)}catch(err){toast(err.message||tr('error'))}};document.getElementById('logout').onclick=async()=>{await sb.auth.signOut();location.hash='';location.reload()};document.getElementById('forgotBtn').onclick=async()=>{const email=prompt(state.lang==='ar'?'أدخل بريدك الإلكتروني':'Enter your email');if(!email)return;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.href.split('#')[0]+'#reset-password'});if(error)console.error(error);toast(tr('resetSent'))};
applyLang();
sb.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){document.getElementById('authView').classList.add('hidden');document.getElementById('resetView').classList.remove('hidden')}});
sb.auth.getSession().then(async({data})=>{if(data.session){if(location.hash==='#reset-password'){document.getElementById('authView').classList.add('hidden');document.getElementById('resetView').classList.remove('hidden')}else await showApp()}});
